# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 06:48
from __future__ import unicode_literals

import chanwoo.mall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image1',
            field=models.ImageField(upload_to=chanwoo.mall.models.random_directory_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=chanwoo.mall.models.random_directory_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=chanwoo.mall.models.random_directory_path),
        ),
    ]
